giantswarm/observability-bundle

- CHANGELOG.md
- helm/observability-bundle/templates/apps.yaml
This PR:
- changes helm default timeouts (5min) to 10min
> Tune helm timeout

- CHANGELOG.md
- helm/observability-bundle/templates/apps.yaml
- helm/observability-bundle/values.yaml
This PR:
* adds app dependency annotations to ensure the operator and the agent are deployed after the CRDs are applied
> Configure app dependency

- CHANGELOG.md
- helm/observability-bundle/values.yaml
This PR towards https://github.com/giantswarm/giantswarm/issues/26221:
* updates the prometheus operator app
> Upgrade prometheus operator app

- CHANGELOG.md
- helm/observability-bundle/values.yaml
Update KSM ServiceMonitor
towards:
https://github.com/giantswarm/giantswarm/issues/27228
https://github.com/giantswarm/giantswarm/issues/27196
https://github.com/giantswarm/giantswarm/issues/27181
> Upgrade prometheus-operator-app to 5.0.5

- CHANGELOG.md
- helm/observability-bundle/values.yaml
> Upgrade promtail

- CHANGELOG.md
- helm/observability-bundle/templates/prometheus-agent-extraconfig.yaml
- helm/observability-bundle/values.yaml
This PR:
* fixes missing external labels
> Fix missing external labels by not providing a nil override

- CHANGELOG.md
- helm/observability-bundle/values.yaml
towards https://github.com/giantswarm/giantswarm/issues/28239
> Bump prometheus-agent to 0.6.4

- CHANGELOG.md
- helm/observability-bundle/values.yaml
> Upgrade apps

- CHANGELOG.md
- helm/observability-bundle/templates/prometheus-operator-extraconfig.yaml
This PR:
*fixes KSM psp toggle
> Fix KSM psp toggle

- README.md
- helm/observability-bundle/values.yaml
towards https://github.com/giantswarm/giantswarm/issues/28486
> Add secret to grafana-agent to store logging write credentials

- CHANGELOG.md
- helm/observability-bundle/values.yaml
towards https://github.com/giantswarm/giantswarm/issues/29368
> Bump grafana-agent to 0.3.2

- CHANGELOG.md
- helm/observability-bundle/values.yaml
towards https://gigantic.slack.com/archives/C01176DKNP4/p1706013610632959
This PR:
> Bump kube-prometheus-stack to 8.1.3 (gsoci registry)

- helm/observability-bundle/values.yaml
This PR:
* fixes renovate comment
> Fix renovate for kube-prometheus-stack

- CHANGELOG.md
- helm/observability-bundle/values.yaml
towards https://github.com/giantswarm/giantswarm/issues/29530
> Bump kube-prometheus-stack to 9.1.2

- CHANGELOG.md
- helm/observability-bundle/values.yaml
towards https://github.com/giantswarm/giantswarm/issues/31393
> Fix CNP issues in multiple apps

- CHANGELOG.md
Towards: https://github.com/giantswarm/roadmap/issues/3522
> Fix CHANGELOG entry for alloy-metrics

- helm/observability-bundle/values.yaml
Fix alloy metrics app catalog
This PR:
> fix alloy metrics app catalog

- CHANGELOG.md
Add changelog entry for https://github.com/giantswarm/observability-bundle/pull/241
> add CHANGELOG entry for #241

- CHANGELOG.md
- helm/observability-bundle/values.yaml
This PR:
* adds the missing depends on annotations on alloy logs and alloy metrics to ensure the apps are deployed after the crds are deployed
> add missing depends on annotation

- CHANGELOG.md
- helm/observability-bundle/values.yaml
Towards https://github.com/giantswarm/roadmap/issues/3750
This PR adds `alloy-events` app in the bundle.
> add alloy-events app in the bundle

- CHANGELOG.md
- helm/observability-bundle/ksm-configurations/flux_alert.yaml
- helm/observability-bundle/ksm-configurations/flux_bucket.yaml
- helm/observability-bundle/ksm-configurations/flux_gitrepository.yaml
- helm/observability-bundle/ksm-configurations/flux_helmchart.yaml
- helm/observability-bundle/ksm-configurations/flux_helmrelease.yaml
- helm/observability-bundle/ksm-configurations/flux_helmrepository.yaml
- helm/observability-bundle/ksm-configurations/flux_imagepolicy.yaml
- helm/observability-bundle/ksm-configurations/flux_imagerepository.yaml
- helm/observability-bundle/ksm-configurations/flux_imageupdateautomation.yaml
- helm/observability-bundle/ksm-configurations/flux_kustomization.yaml
- helm/observability-bundle/ksm-configurations/flux_ocirepository.yaml
- helm/observability-bundle/ksm-configurations/flux_provider.yaml
- helm/observability-bundle/ksm-configurations/flux_receiver.yaml
> Reconfiguring KSM

- CHANGELOG.md
- helm/observability-bundle/ksm-configurations/irsa.yaml
Towards https://github.com/giantswarm/giantswarm/issues/33870
This PR:
> Add KSM metrics for IRSAClaim objects

- CHANGELOG.md
- helm/observability-bundle/values.yaml
Includes https://github.com/giantswarm/kube-prometheus-stack-app/pull/485
> Upgrade `kube-prometheus-stack-app` to 18.1.0
