CHANGELOG.md
helm/observability-bundle/Chart.yaml
helm/observability-bundle/values.yaml

This PR:
* upgrades prometheus operator app and crd to 3.0.0

Upgrade prometheus-operator to 3.0.0

---

CHANGELOG.md
helm/observability-bundle/values.yaml

Towards https://github.com/giantswarm/giantswarm/issues/25400
This PR:
* Upgrades `prometheus-agent` from to 0.1.7 to 0.2.0 (watchdog addition)

Upgrade prometheus-agent from to 0.1.7 to 0.2.0.

---

CHANGELOG.md
README.md
helm/observability-bundle/values.schema.json
helm/observability-bundle/values.yaml

towards https://github.com/giantswarm/roadmap/issues/2054
This PR:
* add `promtail-app` to the `observability-bundle` and disabled it by default

Add promtail-app to bundle

---

helm/observability-bundle/values.yaml

towards https://github.com/giantswarm/roadmap/issues/2054
This PR:
* fix the `promtail-app` chart name (`promtail` on registry)

Fix promtail chart name

---

CHANGELOG.md
helm/observability-bundle/values.yaml

This PR:
* drops `apiserver_request_slo_duration_seconds_bucket` metrics from apiserver target: high-cardinality and not used.
This metric is the one with the most metrics.
Example on `gauss`:
There's no occurrence of this metric's name in the `prometheus-rules` or the `dashboards` repos.
So I think we can safely drop it.
Towards https://github.com/giantswarm/giantswarm/issues/25937

prometheus-operator: drop unused high-cardinality apiserver metrics

---

CHANGELOG.md
helm/observability-bundle/values.yaml

towards https://github.com/giantswarm/giantswarm/issues/26629
A new version of prometheus-agent has been released to fix the watchdog and the data lost.
We have to update the observability-bundle with this version.

Upgrade prometheus-agent-app to 0.4.0

---

CHANGELOG.md
helm/observability-bundle/values.yaml

towards https://github.com/giantswarm/giantswarm/issues/26674
Bump `prometheus-agent-app` to 0.4.1: fix preStop with removing the wal directory

Bump prometheus-agent-app to 0.4.1

---

CHANGELOG.md
helm/observability-bundle/templates/_helpers.tpl

This PR:
towards https://github.com/giantswarm/giantswarm/issues/26932
Reverting the change which introduced the addition of cluster prefix into the app name as it's causing major issues on several installations.

Revert name change

---

CHANGELOG.md
helm/observability-bundle/templates/prometheus-operator-extraconfig.yaml
helm/observability-bundle/values.yaml

This PR:
* ensures prometheus operator can be used with cilium https://github.com/giantswarm/giantswarm/issues/27646

Enable cilium for prometheus-operator

---

CHANGELOG.md
helm/observability-bundle/Chart.yaml
helm/observability-bundle/values.yaml

To be merged after https://github.com/giantswarm/prometheus-agent-app/pull/74 is released
This PR:
* upgrades prometheus-agent app to 0.6.0

Upgrade prometheus agent app

---

CHANGELOG.md
helm/observability-bundle/templates/promtail-extraconfig.yaml
helm/observability-bundle/values.yaml

This PR:
* upgrades Prometheus operator and CRDS to 6.1.0 (prometheus operator 0.68.0) to fix scraping issues with the cilium network policy
* upgrades Prometheus Agent to 0.6.2 => Prometheus to 2.47.0

Upgrade Apps

---

CHANGELOG.md
helm/observability-bundle/templates/prometheus-operator-extraconfig.yaml

This PR:
* enables the kube-proxy service monitor so we can ignore it in the list of targets from PMO

Enable kube-proxy servicemonitor

---

CHANGELOG.md
helm/observability-bundle/values.yaml

This PR:
* upgrades prometheus-agent to version 0.6.3

Update prometheus agent

---

CHANGELOG.md
helm/observability-bundle/templates/prometheus-agent-extraconfig.yaml
helm/observability-bundle/templates/prometheus-operator-extraconfig.yaml
helm/observability-bundle/templates/promtail-extraconfig.yaml
helm/observability-bundle/values.schema.json
helm/observability-bundle/values.yaml

Towards https://github.com/giantswarm/giantswarm/issues/28337
This PR adds a new switch for PSP disablement to transition to PSS

Disable psp switch

---

CHANGELOG.md
helm/observability-bundle/values.yaml

This PR:
*upgrades the prometheus-agent towards https://github.com/giantswarm/giantswarm/issues/28719

upgrade-agent-0.6.6

---

CHANGELOG.md
helm/observability-bundle/values.yaml

This PR:
* bump `grafana-agent` to 0.3.0.

Bump grafana-agent to 0.3.0

---

CHANGELOG.md
helm/observability-bundle/templates/apps.yaml
helm/observability-bundle/values.schema.json
helm/observability-bundle/values.yaml

This PR:
* extends prometheus-operator-app timeout to avoid race conditions when installing

Extend prometheus-operator-app timeout

---

CHANGELOG.md
helm/observability-bundle/values.yaml

Towards https://github.com/giantswarm/giantswarm/issues/29405
This PR upgrades `promtail` to 1.5.0 and `kube-prometheus-stack` to 8.1.2

upgrade components to latest versions

---

CHANGELOG.md
helm/observability-bundle/templates/observability-bundle-psp-override.yaml
helm/observability-bundle/values.schema.json
helm/observability-bundle/values.yaml

This PR:
* upgrades prometheus operator apps
* adds back pss toggle for capi WCs

Add pss toggle back and upgrade prometheus-operator apps

---

CHANGELOG.md
helm/observability-bundle/values.schema.json
helm/observability-bundle/values.yaml

This PR:
* adds app dependency mechanism to promtail and grafana-agent
This will avoid errors like 
```
$ kubectl get app -n $WCNS $WC-grafana-agent -o yaml
[...]
invalid manifest error: (unable to build kubernetes objects from release manifest: resource mapping not found for name: "grafana-agent" namespace: "" from "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
```

Add missing depends on annotation to promtail and grafana-agent

---

CHANGELOG.md
helm/observability-bundle/values.yaml

towards https://github.com/giantswarm/giantswarm/issues/29665
=> add rollout strategy to prometheus-operator deployment

Bump kube-prometheus-stack to 9.1.0

---

CHANGELOG.md
helm/observability-bundle/values.yaml

This PR:
- bump promtail 1.5.3 (set memory limit to 256Mi)

Bump promtail 1.5.3

---

docs/upgrade.md

Towards https://github.com/giantswarm/giantswarm/issues/30929
This PR:
* adds vpa upgrade process in the observability-bundle migration process.

Add VPA changes to the upgrade docs

---

CHANGELOG.md
helm/observability-bundle/values.yaml

This PR:
* changes prometheus-operator prometheusRules validation to skip promql syntax check for prometheusRules that are labelled `application.giantswarm.io/prometheus-rule-kind: loki`
Towards https://github.com/giantswarm/roadmap/issues/3178

prometheus-operator: skip promql check for loki rules

---

CHANGELOG.md
helm/observability-bundle/Chart.yaml
helm/observability-bundle/values.yaml

Towards: https://github.com/giantswarm/roadmap/issues/3524
This PR adds Alloy application into the observability bundle for it to be used as a logging agent in place of Promtail.

add Alloy app

---

CHANGELOG.md
helm/observability-bundle/values.yaml

Towards: https://github.com/giantswarm/roadmap/issues/3524
The naming style of Alloy app in the observability bundle is wrong as we are using camel case values there.
```
$ k -n=org-giantswarm get cm golem-observability-bundle-logging-extraconfig -oyaml|bl -p
apiVersion: v1
data:
values: |
apps:
alloy-logs:      <--- here
enabled: false
grafanaAgent:
enabled: true
promtail:
enabled: true
kind: ConfigMap
metadata:
name: golem-observability-bundle-logging-extraconfig
namespace: org-giantswarm
```
This PR fixes this issue by renaming alloy-logs app to alloyLogs in the observability bundle applications.

rename alloy-logs to alloyLogs

---

CHANGELOG.md
helm/observability-bundle/values.yaml

Towards: https://github.com/giantswarm/roadmap/issues/3522
Add Alloy as alloy-metrics app in order to use it as a monitoring agent instead of Prometheus Agent.

add alloy-metrics

---

CHANGELOG.md
helm/observability-bundle/values.yaml

Towards: https://github.com/giantswarm/roadmap/issues/3518
This PR upgrade Alloy to version 0.6.1, this brings the following changes:
- allow passing PodLogs via helm chart values
- upgrade to Alloy v1.4.2 which fixes a bug with component reload/evaluation and keeping Alloy up-to-date
- fixes an issue with CiliumNetworkPolicy preventing Alloy to run in clustering mode

Upgrade Alloy to 0.6.1

---

CHANGELOG.md
helm/observability-bundle/values.yaml

This PR:
* makes sure the prometheus-operator does not validate log-based alerts with the new annotation. Migration of our alerts will be done later because we need this prometheus-operator config to be deployed on all MCs before we can proceed

do not validate log based alerts
